"use client";

import { ChangeEvent, DragEvent, useEffect, useRef, useState } from "react";
import { AlertTriangle, ArrowLeft, ArrowRight, CalendarDays, Camera, Check, CheckCircle2, ChevronDown, Circle, FileText, Flag, LockKeyhole, Mail, ParkingCircle, RefreshCw, ScanLine, ShieldCheck, Upload, X } from "lucide-react";
import { DemoCase, DemoRoute, demoCases, matchDemoFile } from "@/lib/demo/demoCases";
import Link from "next/link";
import { connections, scanActions, submissionActions } from "@/lib/demo/automation";
import { AutomationTimeline, ConnectedTools } from "./DemoIntegrations";
import { ThemeToggle } from "./ThemeToggle";

type Screen = "home" | "scan" | "result" | "verify" | "report" | "calendar" | "payment" | "evidence" | "grounds" | "draft" | "email" | "automation" | "done" | "unknown";
const scanSteps = scanActions.map((action) => action.title);

export function ParkPalDemo() {
  const [screen, setScreen] = useState<Screen>("home");
  const [route, setRoute] = useState<DemoRoute>("appeal");
  const [scanStep, setScanStep] = useState(0);
  const [autoStep, setAutoStep] = useState(0);
  const [fileName, setFileName] = useState("");
  const [calendarAdded, setCalendarAdded] = useState(false);
  const [evidenceAdded, setEvidenceAdded] = useState(false);
  const [dragging, setDragging] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);
  const item = demoCases[route];

  useEffect(() => {
    const saved = localStorage.getItem("parkpal-demo");
    if (saved) try { const data = JSON.parse(saved); setRoute(data.route ?? "appeal"); setScreen(data.screen ?? "home"); setCalendarAdded(Boolean(data.calendarAdded)); setEvidenceAdded(Boolean(data.evidenceAdded)); } catch {}
  }, []);
  useEffect(() => { localStorage.setItem("parkpal-demo", JSON.stringify({ route, screen, calendarAdded, evidenceAdded })); }, [route, screen, calendarAdded, evidenceAdded]);

  function start(next: DemoRoute, name = "Demo notice") {
    setRoute(next); setFileName(name); setScanStep(0); setScreen("scan");
    let index = 0;
    const timer = window.setInterval(() => {
      index += 1; setScanStep(index);
      if (index >= scanSteps.length) { window.clearInterval(timer); window.setTimeout(() => setScreen("result"), 350); }
    }, 260);
  }
  function onFile(file?: File) {
    if (!file) return;
    const matched = matchDemoFile(file.name);
    if (matched) start(matched, file.name); else { setFileName(file.name); setScreen("unknown"); }
  }
  function reset() { localStorage.removeItem("parkpal-demo"); setScreen("home"); setRoute("appeal"); setFileName(""); setCalendarAdded(false); setEvidenceAdded(false); }
  function automate() {
    setAutoStep(0); setScreen("automation"); let index = 0;
    const actions = submissionActions[route];
    const timer = window.setInterval(() => { index += 1; setAutoStep(index); if (index >= actions.length) { window.clearInterval(timer); window.setTimeout(() => { setCalendarAdded(true); setScreen("done"); }, 350); } }, 280);
  }

  if (screen !== "home") return <Journey screen={screen} setScreen={setScreen} route={route} item={item} scanStep={scanStep} autoStep={autoStep} fileName={fileName} calendarAdded={calendarAdded} setCalendarAdded={setCalendarAdded} evidenceAdded={evidenceAdded} setEvidenceAdded={setEvidenceAdded} start={start} automate={automate} reset={reset} onFile={onFile} />;

  return <main className="demo-page">
    <header className="demo-nav"><a href="#top" className="demo-logo"><ParkingCircle /> ParkPal</a><div className="demo-nav-actions"><Link href="/pricing">For drivers &amp; fleets</Link><span className="demo-nav-note"><ShieldCheck size={17}/> Secure demo</span><ThemeToggle/></div></header>
    <section id="top" className="scanner-hero">
      <div className="hero-copy"><p className="eyebrow">Parking notice assistant</p><h1>Scan your parking notice</h1><p>ParkPal checks whether it is genuine, tells you what to do, and helps complete the next step.</p></div>
      <div className={`scanner-box ${dragging ? "is-dragging" : ""}`} onDragOver={(e) => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(e: DragEvent) => { e.preventDefault(); setDragging(false); onFile(e.dataTransfer.files[0]); }}>
        <div className="scanner-corners"><ScanLine size={38}/></div><h2>Place your notice here</h2><p>Take a clear photo or choose a PDF, image, or screenshot.</p>
        <div className="scanner-actions"><button className="primary-action" onClick={() => fileRef.current?.click()}><Camera size={20}/> Scan my notice</button><button className="quiet-action" onClick={() => fileRef.current?.click()}><Upload size={19}/> Upload file</button></div>
        <input ref={fileRef} className="sr-only" type="file" accept="image/*,.pdf" onChange={(e: ChangeEvent<HTMLInputElement>) => onFile(e.target.files?.[0])}/>
      </div>
      <p className="reassurance"><LockKeyhole size={16}/> Your notice is analysed securely and you stay in control before any action is taken.</p>
      <div className="demo-picker"><span>Try a demo notice</span><div><button onClick={() => start("scam")}>Suspicious</button><button onClick={() => start("pay")}>Valid to pay</button><button onClick={() => start("appeal")}>May be challenged</button></div></div>
    </section>
    <section className="simple-section"><p className="eyebrow">One clear route</p><h2>From notice to next action</h2><div className="route-line">{[["Scan","We read it"],["Verify","We check it"],["Decide","Scam, pay or challenge"],["Act","We prepare the action"],["Track","You stay on time"]].map(([a,b],i)=><div className="route-stop" key={a}><span>{i+1}</span><strong>{a}</strong><small>{b}</small></div>)}</div></section>
    <section className="outcomes"><div><Flag/><h3>Suspicious</h3><p>Avoid unsafe links and verify the real issuer.</p></div><div><CheckCircle2/><h3>Pay</h3><p>Prepare the official route and save reminders.</p></div><div><FileText/><h3>Challenge</h3><p>Collect evidence, prepare the appeal and track it.</p></div></section>
    <section className="positioning"><h2>ParkPal turns a parking notice into a completed next action.</h2><p>From verification and payment to evidence-led appeals, ParkPal removes the admin drivers normally manage alone.</p></section>
    <section className="business-preview"><div><p className="eyebrow">Drivers and fleets</p><h2>Pay only when you win. Or automate every notice.</h2><p>Individual drivers pay no upfront appeal fee. Professional fleets get deadline, evidence, payment and appeal automation in one place.</p></div><Link href="/pricing" className="primary-action">See pricing <ArrowRight/></Link></section>
    <footer className="demo-footer"><span>© 2026 ParkPal</span><span>Automated guidance and administrative support — not a replacement for qualified legal advice.</span></footer>
    {process.env.NODE_ENV !== "production" && <div className="presenter"><span>Presenter</span><button onClick={() => start("scam")}>Scam</button><button onClick={() => start("pay")}>Pay</button><button onClick={() => start("appeal")}>Appeal</button><button onClick={reset}><RefreshCw size={14}/></button></div>}
  </main>;
}

function Journey({screen,setScreen,route,item,scanStep,autoStep,fileName,calendarAdded,setCalendarAdded,evidenceAdded,setEvidenceAdded,start,automate,reset,onFile}:{screen:Screen;setScreen:(s:Screen)=>void;route:DemoRoute;item:DemoCase;scanStep:number;autoStep:number;fileName:string;calendarAdded:boolean;setCalendarAdded:(v:boolean)=>void;evidenceAdded:boolean;setEvidenceAdded:(v:boolean)=>void;start:(r:DemoRoute,n?:string)=>void;automate:()=>void;reset:()=>void;onFile:(f?:File)=>void}) {
  return <main className="journey-page"><header className="journey-nav"><button onClick={reset} className="demo-logo"><ParkingCircle/> ParkPal</button><div className="journey-actions"><ThemeToggle/><button className="reset-button" onClick={reset}><RefreshCw size={16}/> Reset demo</button></div></header><div className="journey-shell">
    {screen === "scan" && <Panel wide><div className="scan-visual"><ScanLine size={42}/><div className="scan-beam"/></div><p className="eyebrow">Reading {fileName}</p><h1>Checking your notice</h1><AutomationTimeline actions={scanActions} current={scanStep}/></Panel>}
    {screen === "unknown" && <Panel><AlertTriangle className="status-icon amber"/><p className="eyebrow">Demo file not mapped</p><h1>Choose a sample analysis route</h1><p className="lead">We received <strong>{fileName}</strong>, but this frontend demo does not pretend to recognise unknown files.</p><div className="stack-actions"><button onClick={()=>start("scam",fileName)}>Show suspicious route</button><button onClick={()=>start("pay",fileName)}>Show payment route</button><button onClick={()=>start("appeal",fileName)}>Show challenge route</button></div><button className="text-button" onClick={()=>setScreen("home")}><ArrowLeft/> Back</button></Panel>}
    {screen === "result" && <Result item={item} route={route} setScreen={setScreen}/>} 
    {screen === "verify" && <Panel><ShieldCheck className="status-icon amber"/><p className="eyebrow">Official-source check</p><h1>This notice could not be verified safely</h1><p className="lead">ParkPal checked the sender, payment URL, issuer domain, vehicle details, appeal route, amount format and known issuer patterns.</p><ConnectedTools tools={connections.scam}/><div className="safe-note"><LockKeyhole/> No payment or personal information has been shared.</div><button className="primary-action" onClick={()=>setScreen("report")}><Mail/> Prepare a report</button></Panel>}
    {screen === "report" && <EmailCard report item={item} onSend={automate}/>} 
    {screen === "calendar" && <Panel wide><CalendarDays className="status-icon blue"/><p className="eyebrow">Your permission</p><h1>Connect your calendar?</h1><p className="lead">ParkPal will create both deadline events, add the notice reference, official link and amount, then schedule three useful reminders.</p><ConnectedTools tools={connections.pay} permission="Calendar"/><CalendarCard item={item}/><div className="calendar-details"><span><Check/> Discount deadline detected</span><span><Check/> Final deadline detected</span><span><Check/> Official link ready</span><span><Check/> Three reminders ready</span></div><div className="button-row"><button className="primary-action" onClick={()=>{setCalendarAdded(true);setScreen("payment")}}><Check/> Allow and create events</button><button className="quiet-action" onClick={()=>setScreen("payment")}>Not now</button></div></Panel>}
    {screen === "payment" && <Panel wide><CheckCircle2 className="status-icon green"/><p className="eyebrow">Payment prepared</p><h1>Everything is ready</h1><ConnectedTools tools={connections.pay}/><div className="prep-list">{["Official portal found and domain verified",`Reference ${item.referenceNumber} copied`,`${item.vehicleRegistration} copied`,`${item.discountedAmount} amount prepared`,"Non-sensitive fields pre-filled","Ready for your financial approval"].map(x=><div key={x}><Check/>{x}</div>)}</div><div className="browser"><div className="browser-bar"><i/><i/><i/><span><LockKeyhole/> {item.portalUrl}</span></div><div className="portal"><strong>{item.portalName}</strong><p>Notice details have been pre-filled in demo mode.</p><dl><dt>Reference</dt><dd>{item.referenceNumber}</dd><dt>Vehicle</dt><dd>{item.vehicleRegistration}</dd><dt>Amount</dt><dd>{item.discountedAmount}</dd></dl></div></div><p className="fine-print">ParkPal never enters banking credentials. You approve the payment.</p><button className="primary-action" onClick={automate}>Approve demo payment <ArrowRight/></button></Panel>}
    {screen === "evidence" && <EvidenceFlow item={item} added={evidenceAdded} onAdd={()=>setEvidenceAdded(true)} onContinue={()=>setScreen("grounds")}/>} 
    {screen === "grounds" && <Panel wide><CheckCircle2 className="status-icon green"/><p className="eyebrow">Evidence reviewed</p><h1>You have strong supporting evidence</h1><div className="ground"><small>Strong ground</small><h3>Parking had already been paid for</h3><p>Your receipt shows a valid parking session during the time stated on the notice.</p></div><div className="ground secondary"><small>Supporting ground</small><h3>Notice details may not match the payment record</h3><p>The vehicle and payment details should be reviewed together.</p></div><details><summary>Why ParkPal reached this conclusion <ChevronDown/></summary><p>The recommendation was checked against ParkPal’s verified parking knowledge base. The live RAG system remains available in the existing case workflow.</p></details><button className="primary-action" onClick={()=>setScreen("draft")}>Prepare my appeal <ArrowRight/></button></Panel>}
    {screen === "draft" && <Draft item={item} onContinue={()=>setScreen("email")}/>} 
    {screen === "email" && <EmailCard item={item} onSend={automate}/>} 
    {screen === "automation" && <Panel wide><Mail className="status-icon blue"/><p className="eyebrow">ParkPal is working</p><h1>{route==="appeal"?"Submitting your appeal":route==="scam"?"Reporting the notice":"Completing payment"}</h1><ConnectedTools tools={connections[route]}/><AutomationTimeline actions={submissionActions[route]} current={autoStep}/></Panel>}
    {screen === "done" && <Done route={route} item={item} calendarAdded={calendarAdded} reset={reset}/>} 
  </div></main>;
}

function Panel({children,wide=false}:{children:React.ReactNode;wide?:boolean}) { return <section className={`journey-panel ${wide?"wide":""}`}>{children}</section> }
function Result({item,route,setScreen}:{item:DemoCase;route:DemoRoute;setScreen:(s:Screen)=>void}) { const scam=route==="scam", pay=route==="pay"; return <Panel wide><div className={`result-mark ${scam?"warning":pay?"success":"appeal"}`}>{scam?<AlertTriangle/>:<ShieldCheck/>}</div><p className="eyebrow">Check complete · {item.noticeType}</p><h1>{scam?"This notice may be unsafe":pay?"This notice appears valid":"You may have grounds to challenge this notice"}</h1><p className="lead">{scam?"We found several warning signs. Do not use the payment link until the issuer has been verified.":pay?"The issuer and details match, and we did not find a strong reason to challenge it.":"We found a possible conflict between the notice and your parking evidence."}</p><div className="notice-summary"><div><small>Issuer</small><strong>{item.issuer}</strong></div><div><small>Amount</small><strong>{item.amount}</strong></div><div><small>{pay?"Discount deadline":"Action deadline"}</small><strong>{item.appealDeadline??"Verify now"}</strong></div><div><small>Reference</small><strong>{item.referenceNumber}</strong></div></div><div className="findings"><h2>What we found</h2>{item.findings.map(x=><p key={x}><Check/>{x}</p>)}</div><div className="button-row"><button className="primary-action" onClick={()=>setScreen(scam?"verify":pay?"calendar":"evidence")}>{scam?"Verify through official source":pay?"Yes, prepare it":"Build my appeal"}<ArrowRight/></button>{scam&&<button className="quiet-action" onClick={()=>setScreen("report")}>Report this notice</button>}</div></Panel> }
function CalendarCard({item}:{item:DemoCase}) { return <div className="calendar-card"><div><span>22</span><small>JUL</small></div><section><strong>PCN discount deadline</strong><p>{item.discountedAmount} · {item.issuer}</p><small>Reminders: 7 days before, 1 day before, deadline morning</small></section></div> }
function EvidenceFlow({item,added,onAdd,onContinue}:{item:DemoCase;added:boolean;onAdd:()=>void;onContinue:()=>void}) { return <Panel><p className="eyebrow">Step 1 of 2 · Evidence</p><h1>Did you pay for parking?</h1><p className="lead">Add the receipt or app screenshot that covers the time on the notice.</p><button className={`evidence-upload ${added?"added":""}`} onClick={onAdd}>{added?<><CheckCircle2/><strong>Payment receipt added</strong><span>parking-receipt-demo.png · Strong supporting evidence</span></>:<><Upload/><strong>Add receipt or screenshot</strong><span>For this demo, any selected upload adds the sample receipt.</span></>}</button><div className="evidence-status"><span><Check/> Notice added</span><span className={added?"done":""}>{added?<Check/>:<Circle/>} Payment proof {added?"added":"needed"}</span><span><Circle/> Signage photo optional</span></div><button className="primary-action" disabled={!added} onClick={onContinue}>Review my evidence <ArrowRight/></button></Panel> }
function Draft({item,onContinue}:{item:DemoCase;onContinue:()=>void}) { return <Panel wide><p className="eyebrow">Appeal prepared</p><h1>Review your appeal</h1><div className="letter"><div><strong>To</strong><span>appeals@northstar-parking.demo</span></div><div><strong>Subject</strong><span>Challenge to notice {item.referenceNumber}</span></div><p>Dear Appeals Team,</p><p>I am challenging parking charge {item.referenceNumber} for vehicle {item.vehicleRegistration}. Parking was paid for through the parking app, and the attached receipt shows a valid session covering the time stated on the notice.</p><p>Please review the payment record alongside the notice and cancel the charge. I have attached the payment receipt as supporting evidence.</p><p>Yours faithfully</p><div className="attachment"><FileText/> parking-receipt-demo.png</div></div><div className="review-checks"><span><Check/> Facts confirmed</span><span><Check/> Evidence attached</span><span><Check/> Correct route selected</span><span><Check/> Deadline checked</span></div><button className="primary-action" onClick={onContinue}>Continue to submission <ArrowRight/></button></Panel> }
function EmailCard({item,onSend,report=false}:{item:DemoCase;onSend:()=>void;report?:boolean}) { return <Panel wide><p className="eyebrow">Email preview · Demo only</p><h1>{report?"Report ready to send":"ParkPal has prepared your appeal"}</h1><div className="email-window"><div className="email-head"><Mail/><strong>New message</strong><X/></div><label>To <span>{report?"report@actionfraud.police.uk":"appeals@northstar-parking.demo"}</span></label><label>Subject <span>{report?`Suspicious parking notice ${item.referenceNumber}`:`Appeal — ${item.referenceNumber}`}</span></label><div className="email-body">{report?<p>I received a parking payment request that could not be verified. The payment domain does not match the named issuer and key vehicle details are missing. Please review the attached notice.</p>:<p>Please find my appeal for notice {item.referenceNumber}. The attached payment receipt confirms a valid session at the stated time. I request that the charge is reviewed and cancelled.</p>}</div><div className="attachment"><FileText/>{report?"suspicious-notice.jpg":"parking-receipt-demo.png"}</div></div><button className="primary-action" onClick={onSend}><Mail/> {report?"Send demo report":"Submit my appeal"}</button></Panel> }
function Done({route,item,calendarAdded,reset}:{route:DemoRoute;item:DemoCase;calendarAdded:boolean;reset:()=>void}) { const title=route==="scam"?"You avoided a potentially unsafe payment route":route==="pay"?"Demo payment completed successfully":"Appeal submitted"; return <Panel wide><div className="success-burst"><Check/></div><p className="eyebrow">Action complete · Demo mode</p><h1>{title}</h1><p className="lead">{item.confirmation}</p><div className="confirmation"><div><small>Confirmation reference</small><strong>{route==="appeal"?"APL-2026-4178":route==="pay"?"PAY-842019":"RPT-135906"}</strong></div><div><small>Status</small><strong>{route==="appeal"?"Waiting for operator decision":route==="pay"?"Paid in demo mode":"Reported for review"}</strong></div><div><small>Calendar</small><strong>{calendarAdded?"Reminders added":route==="scam"?"Not needed":"Not added"}</strong></div><div><small>Next step</small><strong>{route==="appeal"?"Response expected in 28 days":"Confirmation saved"}</strong></div></div><div className="timeline"><span className="done">Notice checked</span><span className="done">Action prepared</span><span className="done">Confirmation saved</span>{route==="appeal"&&<span>Waiting for decision</span>}</div><button className="primary-action" onClick={reset}>Scan another notice</button></Panel> }
