"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Building2, Calculator, Car, Check, ParkingCircle } from "lucide-react";
import { ThemeToggle } from "./ThemeToggle";
import { driverPricing, fleetPlans, pricingDetails } from "@/lib/demo/pricing";

export function PricingExperience() {
  const [mode,setMode]=useState<"driver"|"fleet">("driver");
  const [original,setOriginal]=useState(100); const [finalAmount,setFinalAmount]=useState(0);
  const result=useMemo(()=>{const saving=Math.max(0,original-finalAmount),fee=saving*driverPricing.feeRate;return{saving,fee,keeps:saving-fee}},[original,finalAmount]);
  return <main className="pricing-page"><header className="demo-nav"><Link href="/" className="demo-logo"><ParkingCircle/> ParkPal</Link><div className="pricing-nav"><Link href="/">Scan a notice</Link><ThemeToggle/></div></header>
    <section className="pricing-hero"><p className="eyebrow">Clear, transparent pricing</p><h1>Simple pricing for drivers.<br/>Powerful automation for fleets.</h1><p>Pay only for a verified driver saving, or manage every notice across your fleet.</p><div className="customer-toggle"><button className={mode==="driver"?"active":""} onClick={()=>setMode("driver")}><Car/> I’m a driver</button><button className={mode==="fleet"?"active":""} onClick={()=>setMode("fleet")}><Building2/> I manage vehicles</button></div></section>
    {mode==="driver"?<section className="driver-pricing"><div className="success-fee-card"><span>For individual drivers</span><h2>{driverPricing.headline}</h2><p>No upfront appeal fee. When an appeal produces a verified saving, ParkPal receives 20% of the amount cancelled or reduced.</p><ul>{driverPricing.includes.map(x=><li key={x}><Check/>{x}</li>)}<li><Check/> No success fee if the appeal fails</li></ul><small>Success is confirmed by an official cancellation, reduction, operator response, or tribunal decision.</small></div><div className="fee-calculator"><Calculator/><h2>See exactly what you keep</h2><label>Original parking charge <span>£<input type="number" min="0" value={original} onChange={e=>setOriginal(Number(e.target.value))}/></span></label><label>Final amount after appeal <span>£<input type="number" min="0" value={finalAmount} onChange={e=>setFinalAmount(Number(e.target.value))}/></span></label><dl><dt>Total saving</dt><dd>£{result.saving.toFixed(2)}</dd><dt>ParkPal fee (20%)</dt><dd>£{result.fee.toFixed(2)}</dd><dt>Customer keeps</dt><dd>£{result.keeps.toFixed(2)}</dd></dl><small>Transparent example only. This is not financial advice.</small></div></section>:<FleetPricing/>}
    <section className="roi-section"><p className="eyebrow">Why fleets use ParkPal</p><h2>Priced against avoidable admin and escalation</h2><div><article><h3>Reduce admin time</h3><p>Automate sorting, driver follow-up, evidence gathering and letter preparation.</p></article><article><h3>Prevent escalation</h3><p>Track every deadline before charges increase or appeal rights are lost.</p></article><article><h3>Improve challenge quality</h3><p>Standardise evidence-led appeals across the whole fleet.</p></article></div><small>Illustrative example: avoiding £15,000 in monthly penalties and admin costs can make a £1,500 subscription a clear return.</small></section>
    <PricingFAQ/><section className="pricing-cta"><h2>Ready to remove parking-notice admin?</h2><div><Link className="primary-action" href="/">Scan a notice <ArrowRight/></Link><a className="quiet-action" href="mailto:fleets@parkpal.demo">Book a fleet pilot</a></div></section><footer className="demo-footer"><span>© 2026 ParkPal</span><span>Actions remain the driver’s responsibility until submission is confirmed.</span></footer></main>
}
function FleetPricing(){return <section className="fleet-pricing"><div className="plan-grid">{fleetPlans.map(p=><article className={p.featured?"featured":""} key={p.name}>{p.featured&&<span className="popular">Most popular</span>}<h2>{p.name}</h2><p>{p.audience}</p><strong>{p.price}<small>{p.cadence}</small></strong><b>{p.volume}</b><ul>{p.features.map(x=><li key={x}><Check/>{x}</li>)}</ul><a href="mailto:fleets@parkpal.demo" className={p.featured?"primary-action":"quiet-action"}>Start a pilot</a></article>)}</div><div className="pricing-notes"><p><strong>Additional usage</strong>{pricingDetails.overage}</p><p><strong>Enterprise onboarding</strong>{pricingDetails.onboarding}</p><p><strong>Pilot</strong>{pricingDetails.pilot}</p></div></section>}
function PricingFAQ(){const rows=[["Do drivers pay before appealing?","No. Drivers only pay when an appeal produces a verified saving."],["How is the success fee calculated?","ParkPal charges 20% of the amount cancelled or reduced."],["What if the appeal is unsuccessful?","ParkPal does not charge a B2C success fee."],["What counts as a B2B case?","A notice, payment workflow, appeal, or escalation managed through ParkPal."],["Can a fleet start with a pilot?","Yes. Eligible fleets can use a limited 14-day or 30-day pilot."],["Does ParkPal pay fines for drivers?","No. The driver or authorised representative approves payment."]];return <section className="pricing-faq"><p className="eyebrow">Questions</p><h2>Pricing, without surprises</h2>{rows.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>}
